spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Python spin-fileserver composition example"
name = "spin-fileserver-example"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "spin-fileserver-example"

[component.spin-fileserver-example]
source = "composed.wasm"
files = [{ source = "../static", destination = "/" }]
[component.spin-fileserver-example.build]
command = "componentize-py -d ../wit -w proxy componentize app -o http.wasm && (cd .. && cargo component build --release) && RUST_LOG=error wac plug --plug ../../target/wasm32-wasip1/release/spin_static_fs.wasm http.wasm -o composed.wasm"
watch = ["*.py"]
