spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Rust spin-fileserver composition example"
name = "spin-fileserver-example"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "spin-fileserver-example"

[component.spin-fileserver-example]
source = "target/wasm32-wasip1/release/composed.wasm"
files = [{ source = "../static", destination = "/" }]
[component.spin-fileserver-example.build]
command = "cargo component build --release && (cd .. && cargo component build --release) && RUST_LOG=error wac plug --plug ../../target/wasm32-wasip1/release/spin_static_fs.wasm  target/wasm32-wasip1/release/spin_fileserver_example.wasm -o target/wasm32-wasip1/release/composed.wasm"
watch = ["src/**/*.rs", "Cargo.toml"]
