spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "rust-fileserver-standalone"
description = "An example Rust application using spin-fileserver as a standalone component"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "fs"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.fs]
source = "../../target/wasm32-wasip1/release/spin_static_fs.wasm"
description = "A fileserver component to serve static assets"
files = [{ source = "../static", destination = "/" }]
[component.fs.build]
workdir = "../../"
command = "cargo build --release"

[component.hello]
source = "target/wasm32-wasip1/release/rust_standalone.wasm"
description = "A simple component that returns hello."
[component.hello.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
